name: Build and Release AppImage

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*' ] # Trigger on version tags like v0.1.0
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: "${{ matrix.name }} (${{ matrix.arch }})"
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-latest
            name: "Build AppImage"
            arch: x86_64
#          - runs-on: ubuntu-24.04-arm
#            name: "Build AppImage"
#            arch: aarch64
    container: ghcr.io/pkgforge-dev/archlinux:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies for GTK4/libadwaita and build ui
        run: chmod +x ./get-dependencies.sh && ./get-dependencies.sh

      - name: Run build script
        run: chmod +x ./lsfg-ui-appimage.sh && ./lsfg-ui-appimage.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: AppImage-${{ matrix.arch }}
          path: 'dist'

      - name: Upload version file
        uses: actions/upload-artifact@v4.6.2
        with:
          name: version
          path: ~/version
          overwrite: true

  release:
    if: ${{ github.ref_name == 'main' }}
    needs: [build]
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4.3.0
        with:
          name: AppImage-x86_64

#      - uses: actions/download-artifact@v4.3.0
#        with:
#          name: AppImage-aarch64

      - uses: actions/download-artifact@v4.3.0
        with:
          name: version

      - name: Read version and Get date
        run: |
          echo "VERSION=$(cat version)" >> "${GITHUB_ENV}"
          echo "DATE=$(date +'%Y-%m-%d_%s')" >> "${GITHUB_ENV}"

      - name: Release Artifacts
        uses: softprops/action-gh-release@v2.2.2
        with:
          name: "lsfg-vk-ui: ${{ env.VERSION }}"
          tag_name: "${{ env.VERSION }}@${{ env.DATE }}"
          prerelease: false
          draft: false
          generate_release_notes: false
          make_latest: true
          files: |
            *.AppImage*
