name: Build and Release AppImage

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*' ] # Trigger on version tags like v0.1.0
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  build:
    name: "${{ matrix.name }} (${{ matrix.arch }})"
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-latest
            name: "Build AppImage"
            arch: x86_64
#          - runs-on: ubuntu-24.04-arm
#            name: "Build AppImage"
#            arch: aarch64
    container: ghcr.io/pkgforge-dev/archlinux:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies for GTK4/libadwaita and build ui
        run: |
          pacman -Syu --noconfirm \
          	base-devel        \
          	cargo             \
          	curl              \
          	git               \
          	gtk4              \
          	libadwaita        \
          	libxtst           \
          	pipewire-audio    \
          	pulseaudio        \
          	wget              \
          	xorg-server-xvfb  \
          	zsync

      - name: Run build script
        run: chmod +x ./lsfg-ui-appimage.sh && ./lsfg-ui-appimage.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: AppImage-${{ matrix.arch }}
          path: 'dist'

      - name: Upload version file
        uses: actions/upload-artifact@v4.6.2
        with:
          name: version
          path: ~/version
          overwrite: true
